### ISSUE TITLE
.pnpmfile.cjs wrong package path

### ISSUE THREAD

**Issue by dmitriyzhirma** [mattjennings/svelte-pixi#15]
Actuall path:

```
file:../../package
```

Expected path: 

```
file:../../package
```

**Comment by mattjennings** [comment]
I'm confused, what's the issue you're having? You have the same path for both expected and actual. The path seems to be working as expected for me

**Comment by mattjennings** [comment]
I believe this is fixed now, let me know if you run into any other issues
