### ISSUE TITLE
getApplication() → getApp() on website

### ISSUE THREAD

**Issue by josiahdowdy** [mattjennings/svelte-pixi#20]
<img width="415" alt="sc 59" src="https://user-images.githubusercontent.com/18093109/170774813-47e0923b-588e-4b90-b8e1-e9ec0c9e8e93.png">

Hi, I noticed that on the website the "getApplication" needs updated to "getApp".

Amazing work matt and you have saved me so much time and have made coding more enjoyable.

**Comment by mattjennings** [comment]
Oops, good catch. I'll get that fixed this weekend. Thanks!

**Comment by mattjennings** [comment]
fixed
