### ISSUE TITLE
Automatic Resize

### ISSUE THREAD

**Issue by llPekoll** [mattjennings/svelte-pixi#22]
Hi,
I am trying to resize application on the fly,
I've try to do it using
`<svelte:window bind:innerWidth={w} bind:innerHeight={h} /> `
even tryied 
`onMount(aync()=>{window.innerWidth={w};})`
then
<Application width={w} height={h}  antialias>
But it seems that the Application component is initialized before that.
also, try resizeTo according to the doc
```
onMount(async()=>{
     html = window.HTMLElement
})   
<Application width={w} height={h}  antialias resizeTo={html}>
```
I didn't find the proper way to do it.
Could you help me, please?

**Comment by mattjennings** [comment]
@llPekoll For now you can dynamically resize by binding to the Application instance and calling `app.renderer.resize()`.  

```svelte
<script>
import { Application } from 'svelte-pixi'
let app
let width
let height

$: if (app && width && height) {
  app.renderer.resize(width, height)
}
</script>

<svelte:window bind:innerHeight={height} bind:innerWidth={width} />
<Application bind:instance={app}>
</Application>
```

I'll consider adding this as the behaviour for the width/height props, I think it makes sense to do that. Currently the Application component more-or-less just sends the props to `new PIXI.Application` and has no reactivity on them after that.
