### ISSUE TITLE
Trouble getting started with SvelteKit

### ISSUE THREAD

**Issue by hellostorman** [mattjennings/svelte-pixi#25]
Hi there, I'm unable to get Svelte-Pixi running with SvelteKit, both with your example template and importing into an existing one.

**Your example project**

after cloning the sveltekit project and running npm install I get:
```
npm ERR! code 1
npm ERR! path D:\Dropbox\dev\pixi-test2\node_modules\@sveltejs\kit
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node svelte-kit.js sync
npm ERR! > config.kit.vite has been removed — use vite.config.js instead
npm ERR!     at file:///D:/Dropbox/dev/pixi-test2/node_modules/@sveltejs/kit/src/core/config/options.js:482:10
npm ERR!     at file:///D:/Dropbox/dev/pixi-test2/node_modules/@sveltejs/kit/src/core/config/options.js:374:43
npm ERR!     at file:///D:/Dropbox/dev/pixi-test2/node_modules/@sveltejs/kit/src/core/config/options.js:360:18
npm ERR!     at file:///D:/Dropbox/dev/pixi-test2/node_modules/@sveltejs/kit/src/core/config/options.js:360:18
npm ERR!     at validate_config (file:///D:/Dropbox/dev/pixi-test2/node_modules/@sveltejs/kit/src/core/config/index.js:85:9)
npm ERR!     at process_config (file:///D:/Dropbox/dev/pixi-test2/node_modules/@sveltejs/kit/src/core/config/index.js:62:20)
npm ERR!     at load_config (file:///D:/Dropbox/dev/pixi-test2/node_modules/@sveltejs/kit/src/core/config/index.js:54:9)
npm ERR!     at async file:///D:/Dropbox/dev/pixi-test2/node_modules/@sveltejs/kit/src/cli.js:54:19
```

**Pre-existing SvelteKit project**

No problems with `npm install pixi.js svelte-pixi` but the skeleton project from the SvelteKit site has both a vite.config.js and a svelte.config.js
After changing the vite.config.js to
```
import { sveltekit } from '@sveltejs/kit/vite';

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit()],
	optimizeDeps: {
		include: ['pixi.js'],
	  },
};

export default config;
```
I recieve an error 500 document is not defined, when testing using an example from your documentation.

When changing svelte.config.js to
```
import adapter from '@sveltejs/adapter-auto'

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    adapter: adapter(),
    vite: {
      optimizeDeps: {
        include: ['pixi.js'],
      },
    },
  },
}

export default config
```
I get:
```
 error when starting dev server:
Error: config.kit.vite has been removed — use vite.config.js instead
```

Any help would be really appreciated! I'm a bit new to all this so there's a good chance I just did a step wrong.

**Comment by mattjennings** [comment]
Hey @hellostorman - yeah Kit has seen many breaking changes since I last made the example so I'll have to update it. I'll try to get to that this week!

For the meantime, your best bet would be to create a new Kit project using `npm create svelte@latest my-app` and copying the `optimizeDeps` part into `vite.config.js`:

```
optimizeDeps: {
    include: ['pixi.js'],
},
```

and then copying the contents of `routes/index.svelte` into what is now `routes/+page.svelte`, as well as `lib/PixiApp.svelte`. That _should_ work - but if it doesn't, I'll see what happens when I get to updating the example.

**Comment by mattjennings** [comment]
I've updated the template now - give it a try and see how it goes

**Comment by hellostorman** [comment]
Appreciate it Matt! I'll let you know how it goes

**Comment by hellostorman** [comment]
Seems to be working like a charm. Thanks for getting onto that so fast!

**Comment by mattjennings** [comment]
Fantastic!
