### ISSUE TITLE
PixiJS v8

### ISSUE THREAD

**Issue by scrodde** [mattjennings/svelte-pixi#39]
Love your work! Any plans on supporting PixiJS v8? 

Is https://github.com/mattjennings/svelte-pixi/pull/36 something I could continue to work on to migrate for v8?

**Comment by mattjennings** [comment]
Oh! I hadn't realized PixiJS v8 launched already. I was hoping to coincide v8 support with a [Svelte 5](https://github.com/mattjennings/svelte-pixi/tree/svelte-5) migration as well, as that offered a nice performance boost, but I haven't kept up with where Svelte 5 is at regarding a stable release.

Definitely happy to take any help regarding this though. #36 is more-or-less good to go... I was waiting to hear back from some folk for feedback and never did. It's _probably_ good enough to release and then start on v8, or maybe it's worth skipping v7 altogether?

**Comment by scrodde** [comment]
Better release often. I would merge #36 if that is is good to go and then start a new branch for v8 and another for svelte5? I can help on the v8 migration :)

**Comment by notYou263** [comment]
I was interested in using svelte-pixi with PixiJS v8. I uploaded an updated version [here](https://github.com/notYou263/svelte-pixijs)

I could not set up this repo for development on my machine.
I just set up a new svelte-package and copied the lib from the svelte-5 branch to work on.  
Much love to you for this project. Svelte ♥️PixiJS

**Comment by mattjennings** [comment]
v7.0.0 has been released just so it's available for people to use if they need. All effort is on v8 upgrade now, and then Svelte 5.
